name: agii_alpha
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

# Dependencias utilizadas en esta aplicación
dependencies:

  flutter:
    sdk: flutter
  flutter_native_splash: any # ya no se usa, se reemplazo por ventanas normales
  syncfusion_flutter_charts: ^20.3.48 # usado para diagramar los graficos y hacer la exportación de la imagen
  path_provider: ^2.0.9 # apoyo para la exportación de la imagen del gráfico al dispositivo
  syncfusion_flutter_pdf: ^20.1.48 # se planeaba generar un pdf pero por tiempo no se alcanzo, sin embargo la dependencia quedó acá, actualmente no se usa
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  expandable: ^5.0.1

  url_launcher: ^6.1.6 # dependencia que ayuda a abrir el explorador del telefono y redirigir a sibuls

  animate_do: ^3.0.2 # usado en las animaciones de inicio
  responsive_builder: ^0.4.3 # usado en la implementación de responsividad
  gallery_saver: ^2.3.2 # usado en la función de guardado de imagen 
  screenshot: ^1.2.3 # usado en la función de guardado de imagen
  image_gallery_saver: ^1.7.1  # usado en la función de guardado de imagen
  permission_handler: ^10.2.0 # usado para guardar imagenes, tiene mas relación con los permisos del dispositivo



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.11.0" # dependencia para reemplazar el icono de la aplicación


flutter_native_splash: # ya no se está usando, tiene que ver con el native splash
  color: "#ffffff" #fondo blanco
  image: assets/splash7.png
    

flutter_icons:  # dependencia para reemplazar el icono de la aplicación
  android: "launcher_icon"
  image_path: "assets/logofinal.png"
  min_sdk_android: 21

flutter:
  assets:
    - assets/
  uses-material-design: true

  fonts: #fuente usada por la umd 
    - family: MuseoSansItalic
      fonts:
        - asset: fonts/MuseoSans_500_Italic.otf
    - family: MuseoSans
      fonts:
        - asset: fonts/MuseoSans-300.otf
      
