name: agii_alpha
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'


dependencies:

  flutter:
    sdk: flutter
  flutter_native_splash: any
  syncfusion_flutter_charts: ^20.3.48
  path_provider: ^2.0.9
  syncfusion_flutter_pdf: ^20.1.48
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  expandable: ^5.0.1

  url_launcher: ^6.1.6

  animate_do: ^3.0.2
  responsive_builder: ^0.4.3



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.10.0"


flutter_native_splash:
  color: "#ffffff" #fondo blanco
  image: assets/splash7.png
    

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  assets:
    - assets/
  uses-material-design: true
